#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH="$PATH:${HOME}/bin"
export PATH="$PATH:${HOME}/.local/bin"
export PATH="$PATH:/opt/nvim-linux64/bin"

export XDG_RUNTIME_DIR=/tmp/runtime-dir

# aliases
alias kdbx-get="rm -f ${HOME}/Documents/personal.kdbx && dbxcli get personal.kdbx ${HOME}/Documents/personal.kdbx"
alias kdbx-put="dbxcli put ${HOME}/Documents/personal.kdbx"
alias refresh="source ${HOME}/.zshrc"
alias config="gvim ${HOME}/.zshrc"
alias dn="dotnet"
